"""phase2_brochures_offers

Revision ID: 3d1466261c04
Revises: b59ad6b5be07
Create Date: 2026-05-28 13:26:22.503985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d1466261c04'
down_revision: Union[str, None] = 'b59ad6b5be07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brochures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('brochure_id_kaufda', sa.String(length=200), nullable=False),
    sa.Column('retailer_name', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.String(length=20), nullable=True),
    sa.Column('valid_to', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brochures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brochures_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_brochures_store'), ['store'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brochure_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('price_text', sa.String(length=80), nullable=True),
    sa.Column('quantity_text', sa.String(length=200), nullable=True),
    sa.Column('base_price', sa.String(length=80), nullable=True),
    sa.Column('hint', sa.String(length=300), nullable=True),
    sa.Column('store', sa.String(length=20), nullable=False),
    sa.Column('live_from_date', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('is_cooking_relevant', sa.Boolean(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brochure_id'], ['brochures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_brochure_id'), ['brochure_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_brochure_id'))

    op.drop_table('offers')
    with op.batch_alter_table('brochures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brochures_store'))
        batch_op.drop_index(batch_op.f('ix_brochures_postal_code'))

    op.drop_table('brochures')
    # ### end Alembic commands ###
