"""phase1_auth

Revision ID: b59ad6b5be07
Revises: 04575b18ba54
Create Date: 2026-05-28 13:12:29.847645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b59ad6b5be07'
down_revision: Union[str, None] = '04575b18ba54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=72), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_households_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_households_username'), ['username'], unique=True)

    op.create_table('invite_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['households.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('password_resets',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('profiles',
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('kids', sa.Integer(), nullable=False),
    sa.Column('diet', sa.String(length=20), nullable=False),
    sa.Column('allergies_json', sa.Text(), nullable=False),
    sa.Column('allowed_meats_json', sa.Text(), nullable=False),
    sa.Column('max_cook_time_min', sa.Integer(), nullable=False),
    sa.Column('preferred_cuisines_json', sa.Text(), nullable=False),
    sa.Column('no_gos_json', sa.Text(), nullable=False),
    sa.Column('budget_sensitivity', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('selected_stores_json', sa.Text(), nullable=False),
    sa.Column('monday_only_offers', sa.Boolean(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('household_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_household_id'), ['household_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_household_id'))

    op.drop_table('user_sessions')
    op.drop_table('profiles')
    op.drop_table('password_resets')
    op.drop_table('invite_tokens')
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_households_username'))
        batch_op.drop_index(batch_op.f('ix_households_email'))

    op.drop_table('households')
    # ### end Alembic commands ###
